from __future__ import annotations

from io import BytesIO

import streamlit as st

from pdf_chatbot.assistant import answer_question
from pdf_chatbot.documents import extract_pdf_pages, split_pages
from pdf_chatbot.retrieval import rank_chunks

st.set_page_config(page_title="PDF Chat", page_icon="📄", layout="wide")


@st.cache_data(show_spinner=False)
def index_file(filename: str, content: bytes):
    pages = extract_pdf_pages(BytesIO(content))
    return split_pages(pages, source_name=filename)


def initialise_state() -> None:
    st.session_state.setdefault("chunks", [])
    st.session_state.setdefault("messages", [])


initialise_state()
st.title("PDF Chat")
st.caption("A local-first PDF question-answering demo with transparent citations.")

with st.sidebar:
    st.header("Documents")
    uploads = st.file_uploader("Upload one or more PDFs", type="pdf", accept_multiple_files=True)
    if st.button("Index documents", type="primary", disabled=not uploads):
        chunks = []
        unreadable = []
        for upload in uploads or []:
            try:
                file_chunks = index_file(upload.name, upload.getvalue())
                if file_chunks:
                    chunks.extend(file_chunks)
                else:
                    unreadable.append(upload.name)
            except Exception:
                unreadable.append(upload.name)
        st.session_state.chunks = chunks
        st.session_state.messages = []
        if chunks:
            st.success(f"Indexed {len(chunks)} passages from {len(uploads or []) - len(unreadable)} PDF(s).")
        if unreadable:
            st.warning("No readable text found in: " + ", ".join(unreadable))
    if st.session_state.chunks:
        st.caption(f"{len(st.session_state.chunks)} passages are ready to search.")
        st.caption("Install and run Ollama for generated answers; retrieval works without it.")

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

question = st.chat_input("Ask a question about your PDFs", disabled=not st.session_state.chunks)
if question:
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)
    with st.chat_message("assistant"):
        with st.spinner("Searching your documents…"):
            ranked = rank_chunks(st.session_state.chunks, question)
            answer, used_ollama = answer_question(question, ranked)
        st.markdown(answer)
        st.caption("Answer generated by Ollama." if used_ollama else "Showing retrieved passages (Ollama is optional).")
        if ranked:
            with st.expander("Sources"):
                for item in ranked:
                    st.markdown(f"**{item.chunk.source_name}, page {item.chunk.page_number}** — relevance {item.score:.0%}")
    st.session_state.messages.append({"role": "assistant", "content": answer})
