name: Trigger auto deployment for aci

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aci-AutoDeployTrigger-16bf543b-6c41-4bf8-bd2b-e798b3efc6ac.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.ACI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACI_REGISTRY_PASSWORD }}
          containerAppName: aci
          resourceGroup: azurelearnml
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


